//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWNegocioBanco.SWNegocioBanco {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWNegocioBanco.ISWNegocioBanco")]
    public interface ISWNegocioBanco {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarBanco", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarBancoResponse")]
        EntidadNegocio.Banco.Response.BancoResponse ConsultarBanco(EntidadNegocio.Banco.Request.BancoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarBanco", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarBancoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Banco.Response.BancoResponse> ConsultarBancoAsync(EntidadNegocio.Banco.Request.BancoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarSucursal", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarSucursalResponse")]
        EntidadNegocio.Sucursal.Response.SucursalResponse ConsultarSucursal(EntidadNegocio.Sucursal.Request.SucursalRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarSucursal", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarSucursalResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Sucursal.Response.SucursalResponse> ConsultarSucursalAsync(EntidadNegocio.Sucursal.Request.SucursalRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarOrdenPago", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarOrdenPagoResponse")]
        EntidadNegocio.OrdenPago.Response.OrdenPagoResponse ConsultarOrdenPago(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarOrdenPago", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarOrdenPagoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.OrdenPago.Response.OrdenPagoResponse> ConsultarOrdenPagoAsync(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarMoneda", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarMonedaResponse")]
        EntidadNegocio.Moneda.Response.MonedaResponse ConsultarMoneda(EntidadNegocio.Moneda.Request.MonedaRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarMoneda", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarMonedaResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Moneda.Response.MonedaResponse> ConsultarMonedaAsync(EntidadNegocio.Moneda.Request.MonedaRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarEstado", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarEstadoResponse")]
        EntidadNegocio.Estado.Response.EstadoResponse ConsultarEstado(EntidadNegocio.Estado.Request.EstadoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ConsultarEstado", ReplyAction="http://tempuri.org/ISWNegocioBanco/ConsultarEstadoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Estado.Response.EstadoResponse> ConsultarEstadoAsync(EntidadNegocio.Estado.Request.EstadoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarBanco", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarBancoResponse")]
        EntidadNegocio.Banco.Response.BancoResponse RegistrarBanco(EntidadNegocio.Banco.Request.BancoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarBanco", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarBancoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Banco.Response.BancoResponse> RegistrarBancoAsync(EntidadNegocio.Banco.Request.BancoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarSucursal", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarSucursalResponse")]
        EntidadNegocio.Sucursal.Response.SucursalResponse RegistrarSucursal(EntidadNegocio.Sucursal.Request.SucursalRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarSucursal", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarSucursalResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Sucursal.Response.SucursalResponse> RegistrarSucursalAsync(EntidadNegocio.Sucursal.Request.SucursalRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarEstado", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarEstadoResponse")]
        EntidadNegocio.Estado.Response.EstadoResponse RegistrarEstado(EntidadNegocio.Estado.Request.EstadoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarEstado", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarEstadoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Estado.Response.EstadoResponse> RegistrarEstadoAsync(EntidadNegocio.Estado.Request.EstadoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarMoneda", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarMonedaResponse")]
        EntidadNegocio.Moneda.Response.MonedaResponse RegistrarMoneda(EntidadNegocio.Moneda.Request.MonedaRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarMoneda", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarMonedaResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Moneda.Response.MonedaResponse> RegistrarMonedaAsync(EntidadNegocio.Moneda.Request.MonedaRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarOrdenPago", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarOrdenPagoResponse")]
        EntidadNegocio.OrdenPago.Response.OrdenPagoResponse RegistrarOrdenPago(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/RegistrarOrdenPago", ReplyAction="http://tempuri.org/ISWNegocioBanco/RegistrarOrdenPagoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.OrdenPago.Response.OrdenPagoResponse> RegistrarOrdenPagoAsync(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarBanco", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarBancoResponse")]
        EntidadNegocio.Banco.Response.BancoResponse ActualizarBanco(EntidadNegocio.Banco.Request.BancoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarBanco", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarBancoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Banco.Response.BancoResponse> ActualizarBancoAsync(EntidadNegocio.Banco.Request.BancoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarSucursal", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarSucursalResponse")]
        EntidadNegocio.Sucursal.Response.SucursalResponse ActualizarSucursal(EntidadNegocio.Sucursal.Request.SucursalRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarSucursal", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarSucursalResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Sucursal.Response.SucursalResponse> ActualizarSucursalAsync(EntidadNegocio.Sucursal.Request.SucursalRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarEstado", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarEstadoResponse")]
        EntidadNegocio.Estado.Response.EstadoResponse ActualizarEstado(EntidadNegocio.Estado.Request.EstadoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarEstado", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarEstadoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Estado.Response.EstadoResponse> ActualizarEstadoAsync(EntidadNegocio.Estado.Request.EstadoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarMoneda", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarMonedaResponse")]
        EntidadNegocio.Moneda.Response.MonedaResponse ActualizarMoneda(EntidadNegocio.Moneda.Request.MonedaRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarMoneda", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarMonedaResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Moneda.Response.MonedaResponse> ActualizarMonedaAsync(EntidadNegocio.Moneda.Request.MonedaRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarOrdenPago", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarOrdenPagoResponse")]
        EntidadNegocio.OrdenPago.Response.OrdenPagoResponse ActualizarOrdenPago(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/ActualizarOrdenPago", ReplyAction="http://tempuri.org/ISWNegocioBanco/ActualizarOrdenPagoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.OrdenPago.Response.OrdenPagoResponse> ActualizarOrdenPagoAsync(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarBanco", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarBancoResponse")]
        EntidadNegocio.Banco.Response.BancoResponse EliminarBanco(EntidadNegocio.Banco.Request.BancoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarBanco", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarBancoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Banco.Response.BancoResponse> EliminarBancoAsync(EntidadNegocio.Banco.Request.BancoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarSucursal", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarSucursalResponse")]
        EntidadNegocio.Sucursal.Response.SucursalResponse EliminarSucursal(EntidadNegocio.Sucursal.Request.SucursalRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarSucursal", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarSucursalResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Sucursal.Response.SucursalResponse> EliminarSucursalAsync(EntidadNegocio.Sucursal.Request.SucursalRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarEstado", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarEstadoResponse")]
        EntidadNegocio.Estado.Response.EstadoResponse EliminarEstado(EntidadNegocio.Estado.Request.EstadoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarEstado", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarEstadoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Estado.Response.EstadoResponse> EliminarEstadoAsync(EntidadNegocio.Estado.Request.EstadoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarMoneda", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarMonedaResponse")]
        EntidadNegocio.Moneda.Response.MonedaResponse EliminarMoneda(EntidadNegocio.Moneda.Request.MonedaRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarMoneda", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarMonedaResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.Moneda.Response.MonedaResponse> EliminarMonedaAsync(EntidadNegocio.Moneda.Request.MonedaRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarOrdenPago", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarOrdenPagoResponse")]
        EntidadNegocio.OrdenPago.Response.OrdenPagoResponse EliminarOrdenPago(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISWNegocioBanco/EliminarOrdenPago", ReplyAction="http://tempuri.org/ISWNegocioBanco/EliminarOrdenPagoResponse")]
        System.Threading.Tasks.Task<EntidadNegocio.OrdenPago.Response.OrdenPagoResponse> EliminarOrdenPagoAsync(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISWNegocioBancoChannel : AWNegocioBanco.SWNegocioBanco.ISWNegocioBanco, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SWNegocioBancoClient : System.ServiceModel.ClientBase<AWNegocioBanco.SWNegocioBanco.ISWNegocioBanco>, AWNegocioBanco.SWNegocioBanco.ISWNegocioBanco {
        
        public SWNegocioBancoClient() {
        }
        
        public SWNegocioBancoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SWNegocioBancoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWNegocioBancoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SWNegocioBancoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EntidadNegocio.Banco.Response.BancoResponse ConsultarBanco(EntidadNegocio.Banco.Request.BancoRequest filtro) {
            return base.Channel.ConsultarBanco(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Banco.Response.BancoResponse> ConsultarBancoAsync(EntidadNegocio.Banco.Request.BancoRequest filtro) {
            return base.Channel.ConsultarBancoAsync(filtro);
        }
        
        public EntidadNegocio.Sucursal.Response.SucursalResponse ConsultarSucursal(EntidadNegocio.Sucursal.Request.SucursalRequest filtro) {
            return base.Channel.ConsultarSucursal(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Sucursal.Response.SucursalResponse> ConsultarSucursalAsync(EntidadNegocio.Sucursal.Request.SucursalRequest filtro) {
            return base.Channel.ConsultarSucursalAsync(filtro);
        }
        
        public EntidadNegocio.OrdenPago.Response.OrdenPagoResponse ConsultarOrdenPago(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro) {
            return base.Channel.ConsultarOrdenPago(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.OrdenPago.Response.OrdenPagoResponse> ConsultarOrdenPagoAsync(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro) {
            return base.Channel.ConsultarOrdenPagoAsync(filtro);
        }
        
        public EntidadNegocio.Moneda.Response.MonedaResponse ConsultarMoneda(EntidadNegocio.Moneda.Request.MonedaRequest filtro) {
            return base.Channel.ConsultarMoneda(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Moneda.Response.MonedaResponse> ConsultarMonedaAsync(EntidadNegocio.Moneda.Request.MonedaRequest filtro) {
            return base.Channel.ConsultarMonedaAsync(filtro);
        }
        
        public EntidadNegocio.Estado.Response.EstadoResponse ConsultarEstado(EntidadNegocio.Estado.Request.EstadoRequest filtro) {
            return base.Channel.ConsultarEstado(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Estado.Response.EstadoResponse> ConsultarEstadoAsync(EntidadNegocio.Estado.Request.EstadoRequest filtro) {
            return base.Channel.ConsultarEstadoAsync(filtro);
        }
        
        public EntidadNegocio.Banco.Response.BancoResponse RegistrarBanco(EntidadNegocio.Banco.Request.BancoRequest filtro) {
            return base.Channel.RegistrarBanco(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Banco.Response.BancoResponse> RegistrarBancoAsync(EntidadNegocio.Banco.Request.BancoRequest filtro) {
            return base.Channel.RegistrarBancoAsync(filtro);
        }
        
        public EntidadNegocio.Sucursal.Response.SucursalResponse RegistrarSucursal(EntidadNegocio.Sucursal.Request.SucursalRequest filtro) {
            return base.Channel.RegistrarSucursal(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Sucursal.Response.SucursalResponse> RegistrarSucursalAsync(EntidadNegocio.Sucursal.Request.SucursalRequest filtro) {
            return base.Channel.RegistrarSucursalAsync(filtro);
        }
        
        public EntidadNegocio.Estado.Response.EstadoResponse RegistrarEstado(EntidadNegocio.Estado.Request.EstadoRequest filtro) {
            return base.Channel.RegistrarEstado(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Estado.Response.EstadoResponse> RegistrarEstadoAsync(EntidadNegocio.Estado.Request.EstadoRequest filtro) {
            return base.Channel.RegistrarEstadoAsync(filtro);
        }
        
        public EntidadNegocio.Moneda.Response.MonedaResponse RegistrarMoneda(EntidadNegocio.Moneda.Request.MonedaRequest filtro) {
            return base.Channel.RegistrarMoneda(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Moneda.Response.MonedaResponse> RegistrarMonedaAsync(EntidadNegocio.Moneda.Request.MonedaRequest filtro) {
            return base.Channel.RegistrarMonedaAsync(filtro);
        }
        
        public EntidadNegocio.OrdenPago.Response.OrdenPagoResponse RegistrarOrdenPago(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro) {
            return base.Channel.RegistrarOrdenPago(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.OrdenPago.Response.OrdenPagoResponse> RegistrarOrdenPagoAsync(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro) {
            return base.Channel.RegistrarOrdenPagoAsync(filtro);
        }
        
        public EntidadNegocio.Banco.Response.BancoResponse ActualizarBanco(EntidadNegocio.Banco.Request.BancoRequest filtro) {
            return base.Channel.ActualizarBanco(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Banco.Response.BancoResponse> ActualizarBancoAsync(EntidadNegocio.Banco.Request.BancoRequest filtro) {
            return base.Channel.ActualizarBancoAsync(filtro);
        }
        
        public EntidadNegocio.Sucursal.Response.SucursalResponse ActualizarSucursal(EntidadNegocio.Sucursal.Request.SucursalRequest filtro) {
            return base.Channel.ActualizarSucursal(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Sucursal.Response.SucursalResponse> ActualizarSucursalAsync(EntidadNegocio.Sucursal.Request.SucursalRequest filtro) {
            return base.Channel.ActualizarSucursalAsync(filtro);
        }
        
        public EntidadNegocio.Estado.Response.EstadoResponse ActualizarEstado(EntidadNegocio.Estado.Request.EstadoRequest filtro) {
            return base.Channel.ActualizarEstado(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Estado.Response.EstadoResponse> ActualizarEstadoAsync(EntidadNegocio.Estado.Request.EstadoRequest filtro) {
            return base.Channel.ActualizarEstadoAsync(filtro);
        }
        
        public EntidadNegocio.Moneda.Response.MonedaResponse ActualizarMoneda(EntidadNegocio.Moneda.Request.MonedaRequest filtro) {
            return base.Channel.ActualizarMoneda(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Moneda.Response.MonedaResponse> ActualizarMonedaAsync(EntidadNegocio.Moneda.Request.MonedaRequest filtro) {
            return base.Channel.ActualizarMonedaAsync(filtro);
        }
        
        public EntidadNegocio.OrdenPago.Response.OrdenPagoResponse ActualizarOrdenPago(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro) {
            return base.Channel.ActualizarOrdenPago(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.OrdenPago.Response.OrdenPagoResponse> ActualizarOrdenPagoAsync(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro) {
            return base.Channel.ActualizarOrdenPagoAsync(filtro);
        }
        
        public EntidadNegocio.Banco.Response.BancoResponse EliminarBanco(EntidadNegocio.Banco.Request.BancoRequest filtro) {
            return base.Channel.EliminarBanco(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Banco.Response.BancoResponse> EliminarBancoAsync(EntidadNegocio.Banco.Request.BancoRequest filtro) {
            return base.Channel.EliminarBancoAsync(filtro);
        }
        
        public EntidadNegocio.Sucursal.Response.SucursalResponse EliminarSucursal(EntidadNegocio.Sucursal.Request.SucursalRequest filtro) {
            return base.Channel.EliminarSucursal(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Sucursal.Response.SucursalResponse> EliminarSucursalAsync(EntidadNegocio.Sucursal.Request.SucursalRequest filtro) {
            return base.Channel.EliminarSucursalAsync(filtro);
        }
        
        public EntidadNegocio.Estado.Response.EstadoResponse EliminarEstado(EntidadNegocio.Estado.Request.EstadoRequest filtro) {
            return base.Channel.EliminarEstado(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Estado.Response.EstadoResponse> EliminarEstadoAsync(EntidadNegocio.Estado.Request.EstadoRequest filtro) {
            return base.Channel.EliminarEstadoAsync(filtro);
        }
        
        public EntidadNegocio.Moneda.Response.MonedaResponse EliminarMoneda(EntidadNegocio.Moneda.Request.MonedaRequest filtro) {
            return base.Channel.EliminarMoneda(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.Moneda.Response.MonedaResponse> EliminarMonedaAsync(EntidadNegocio.Moneda.Request.MonedaRequest filtro) {
            return base.Channel.EliminarMonedaAsync(filtro);
        }
        
        public EntidadNegocio.OrdenPago.Response.OrdenPagoResponse EliminarOrdenPago(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro) {
            return base.Channel.EliminarOrdenPago(filtro);
        }
        
        public System.Threading.Tasks.Task<EntidadNegocio.OrdenPago.Response.OrdenPagoResponse> EliminarOrdenPagoAsync(EntidadNegocio.OrdenPago.Request.OrdenPagoRequest filtro) {
            return base.Channel.EliminarOrdenPagoAsync(filtro);
        }
    }
}
